export enum ErrorCode {
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  CRYPTO_SYMBOL_ALREADY_EXISTS = 'CRYPTO_SYMBOL_ALREADY_EXISTS',
}
