CREATE TABLE IF NOT EXISTS cryptocurrencies (
  id UUID PRIMARY KEY NOT NULL,
  name VARCHAR(100),
  symbol VARCHAR(10) NOT NULL UNIQUE,
  price NUMERIC(18, 8) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

